apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-phcl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0033-tenant/tkrw-pr712-0075-0033-app/devfile-sample-phcl@sha256:619f39e47ca9acb4eaeb3952c6ab2a4c43d9459c0ab3023fc7d59ef6ffe24096
        name: my-nodejs
        resources: {}
status: {}
